### ISSUE TITLE
remote: warning: only found copies from modified paths due to too many files.

### ISSUE THREAD

**Issue by antonyanimator** [MarcoHess/smeserver-git#1]
Hi Marco,

I've seen this error and I'm pretty sure it's to do with the contrib as I have successfully pushed git repos that are outside of the contrib. Below is the error, it doesn't seem to affect anything and the push and pull works fine.

**09:45:46-root@srv2-sme:/home/e-smith/files/ibays/anim3/html/sites/all/modules$ git push origin anim
Counting objects: 1087, done.
Compressing objects: 100% (1034/1034), done.
Writing objects: 100% (1083/1083), 2.26 MiB | 1.26 MiB/s, done.
Total 1083 (delta 128), reused 333 (delta 32)
remote: warning: only found copies from modified paths due to too many files.
remote: warning: you may want to set your diff.renamelimit variable to at least 1563 and retry the command.
To ssh://root@myserver.com:2790/home/e-smith/files/git/anim.git
   79379ef..a319318  anim -> anim**

**Comment by MarcoHess** [comment]
Hi Antony,

I have seen that error before as well but I have never contributed it to 
a problem in the contrib. It only happened when I was pushing large/many 
changes. I typically followed the instructions to change the 
diff.renamelimit and the problem went away, so I regarded it as a Git 
problem.

It may be that this is a problem in the git http-backend that is causing 
this and this maybe why you don't see it when you use the ssh approach?

Thanks for trying my contrib.

Regards,

Marco

On 11/07/2013 6:32 PM, antonyanimator wrote:

> Hi Marco,
> 
> I've seen this error and I'm pretty sure it's to do with the contrib 
> as I have successfully pushed git repos that are outside of the 
> contrib. Below is the error, it doesn't seem to affect anything and 
> the push and pull works fine.
> 
> 09:45:46-root@srv2-sme:/home/e-smith/files/ibays/anim3/html/sites/all/modules$ 
> git push origin anim
> Counting objects: 1087, done.
> Compressing objects: 100% (1034/1034), done.
> Writing objects: 100% (1083/1083), 2.26 MiB | 1.26 MiB/s, done.
> Total 1083 (delta 128), reused 333 (delta 32)
> remote: warning: only found copies from modified paths due to too many 
> files.
> remote: warning: you may want to set your diff.renamelimit variable to 
> at least 1563 and retry the command.
> To ssh://root@myserver.com 
> mailto:root@myserver.com:2790/home/e-smith/files/git/anim.git
> 79379ef..a319318 anim -> anim
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/MarcoHess/smeserver-git/issues/1.

## 

Marco Hess
Through IP Pty. Ltd.
www.through-ip.com  | marco.hess@through-ip.com
p: +61 407 78 55 66 | f: +61 8 8121 6191

**Comment by antonyanimator** [comment]
Ah cool, thanks for the info, I changed the rename limit and all working good! Thanks for the contrib!!
